Core3RazorPages/Core22MVCIdentity/Areas/Document/Controllers/UserDocumentCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Core22MVCIdentity.Areas.Document.Controllers
{
    public class LocalUserViewModel
    {
        public int Id { get; set; }
    }
    [Area("Document")]
    public class UserDocumentCategoryController : Controller
    {
        [HttpPost]
        public void RemoveAll(LocalUserViewModel data)
        {
           
        }
    }
}

Core3RazorPages/Core22MVCIdentity/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Core22MVCIdentity.Models;
using Core22MVCIdentity.Data;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace Core22MVCIdentity.Controllers
{
    public class ServerModel
    {
        public string serverName { get; set; }
        public string port { get; set; }
    }
    public class HomeController : Controller
    {
        private ApplicationDbContext _context;
        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }
        [Route("{statusCode}")]
        public IActionResult Error(int statusCode = 0)
        {
            switch (statusCode)
            {
                case 404:
                    return View();
                case 500:
                    return View("BadRequest");
            }

            return View("Error");
        }
        public async Task XYZ2(string SName, string CName, Int16 CId)
        {//for route#2
        }
        public async Task XYZ1(string TName, Int64 MId)
        {//for route#1
        }
                public IActionResult Index()
        {
            var panels = _context.Panels
               .Include(p => p.Frame)
               .ToList();
            //string ip = Response.HttpContext.Connection.RemoteIpAddress.ToString();
            //var card = new SpecialCard()
            //{
            //    //SpecialCardText = "special",
            //    Context = "qwe",
            //    Receiver = "hello"
            //};
            //_context.Add(card);
            //_context.SaveChanges();
            ViewData["Session"] = 0;
            return View(new Core22MVCIdentity.Areas.Document.Controllers.LocalUserViewModel() { Id=1});
        }

        [HttpPost]
        public JsonResult Test([FromBody] ServerModel data)
        {
            try
            {
                if (string.IsNullOrEmpty(data.serverName) ||
                    string.IsNullOrEmpty(data.port))
                {
                    return Json(new { Status = "Error", Message = "Missing Data" });
                }
                else
                {
                    return Json(new { Status = "Success", Message = "Got data" });
                }
            }
            catch (Exception e)
            {
                return Json(new { Status = "Error", Message = e.Message });
            }
        }

        [HttpPost]
        public void CreateNewPanel([FromBody]Panels panel)
        {

            _context.Panels.Add(panel);
            _context.SaveChanges();

           // return CreatedAtAction(nameof(GetPanelById), new { id = panel.ID }, panel);
        }
        public IActionResult Privacy()
        {

            //var x = _context.Cards.Where(c=>c.Discriminator)
            var x = _context.Cards.ToList();
            var employee = _context.Cards.OfType<SpecialCard>().ToList();
                //Select(
            //  a => new SpecialCard
            //  {
            //      ID = a.ID,
            //      Receiver = a.Receiver,
            //      Context = a.Context,
            //      SpecialCardText = "Programmer"
            //  }).ToList();
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Core3RazorPages/Core22MVCIdentity/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model Core22MVCIdentity.Areas.Document.Controllers.LocalUserViewModel
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


<input type="button" class="btn btn-outline-success" onclick="validateData();" value="Agregar al carrito" />
<input type="button" class="btn btn-outline-success" onclick="Test();" value="XMLHttpRequest" />

@using (Html.BeginForm("RemoveAll", "UserDocumentCategory", new { area = "Document" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.Id, new { id = "ra-id" })
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                <div class="clearfix">
                    <div class="pull-right">
                        <input name="data" />
                        <input type="submit" value="Add All" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts
    {

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
    @* <script src="sweetalert2/dist/sweetalert2.all.min.js"></script>*@
    <!-- Include a polyfill for ES6 Promises (optional) for IE11 -->
    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.js"></script>

    <script type="text/javascript">
    function validateData() {

        let sesion = @ViewData["Session"];

        if (sesion == 0) {
            Swal.fire({
                type: 'error',
                title: 'Oops...',
                text: '¡Usted no ha iniciado sesión!',
                footer: '<a asp-controller="Home" asp-action="Login">Iniciar sesión</a>'
            })

        }
        }

        function Test() {
            var xmlhttp = new XMLHttpRequest();
            var url = "/Home/Test";
            var input = {};
            input.serverName = "localhost";
            input.port = 5000;
            xmlhttp.onreadystatechange = function () {
                if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                    var jsResp = JSON.parse(xmlhttp.responseText);
                    if (jsResp.Status == "Success") {
                        //show success
                    }
                    else {
                        //show error
                    }
                }
            }
            xmlhttp.open("POST", url, true);
            xmlhttp.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
            xmlhttp.send(JSON.stringify(input));
        }
    </script>
}